# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test MessagePushResponse")

model.instance <- MessagePushResponse$new()

test_that("messageId", {
  # tests for the property `messageId` (integer)

  # uncomment below to test the property 
  #expect_equal(model.instance$`messageId`, "EXPECTED_RESULT")
})

