# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test MessageObject")

model.instance <- MessageObject$new()

test_that("actions", {
  # tests for the property `actions` (Action)
  # action size range is 0,3

  # uncomment below to test the property 
  #expect_equal(model.instance$`actions`, "EXPECTED_RESULT")
})

test_that("channelName", {
  # tests for the property `channelName` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`channelName`, "EXPECTED_RESULT")
})

test_that("content", {
  # tests for the property `content` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`content`, "EXPECTED_RESULT")
})

test_that("createdAt", {
  # tests for the property `createdAt` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`createdAt`, "EXPECTED_RESULT")
})

test_that("id", {
  # tests for the property `id` (integer)

  # uncomment below to test the property 
  #expect_equal(model.instance$`id`, "EXPECTED_RESULT")
})

test_that("title", {
  # tests for the property `title` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`title`, "EXPECTED_RESULT")
})

