# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test MessagePushRequest")

model.instance <- MessagePushRequest$new()

test_that("actions", {
  # tests for the property `actions` (Action)
  # action size range is 0,3

  # uncomment below to test the property 
  #expect_equal(model.instance$`actions`, "EXPECTED_RESULT")
})

test_that("content", {
  # tests for the property `content` (character)
  # message content

  # uncomment below to test the property 
  #expect_equal(model.instance$`content`, "EXPECTED_RESULT")
})

test_that("needPush", {
  # tests for the property `needPush` (character)
  # when value is false, will not send client push

  # uncomment below to test the property 
  #expect_equal(model.instance$`needPush`, "EXPECTED_RESULT")
})

test_that("title", {
  # tests for the property `title` (character)
  # message title

  # uncomment below to test the property 
  #expect_equal(model.instance$`title`, "EXPECTED_RESULT")
})

